// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

const invoke = window.__TAURI_INVOKE__;

export function queryFileSystem(command: FsCommand) {
    return invoke<QueryCommandResponse>("query_file_system", { command })
}

export type FileData = { fileType: FileType; name: string; parentDir: string | null; extension: string | null; path: string }
export type QueryCommandResponse = { directory: { data: FileData; entries: FileData[] } } | { file: { data: FileData } } | "none"
export type FileType = "directory" | "file" | "unknown"
export type FsCommand = "queryRoot" | { queryPath: { path: string } } | { touchFile: TouchCommand } | { touchDirectory: TouchCommand } | { deletePath: { path: string } } | { renamePath: { from: string; to: string } }
export type TouchCommand = { parentDir: string; name: string }
