// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

const invoke = window.__TAURI_INVOKE__;

export function encounter(command: EncounterCommands) {
    return invoke<EncounterCommandResponse>("encounter", { command })
}

export type EncounterCommands = "listEncounter"
export type Character = { id: string; name: string; hp: HitPoints; initiative: number; initiativeModifier: number }
export type Encounter = { id: string; name: string; characters: Character[] }
export type EncounterCommandResponse = { encounterList: { [key: string]: Encounter } }
export type HitPoints = { current: number; total: number; temporary: number }
